version: '3.5'
services:
    backend:
        build: ./backend
        ports:
            - '5000:5000'
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - BACKEND_ACCESSTOKEN_SECRET_KEYFILE
        secrets:
            - backend_accesstoken_keyfile
        volumes:
            - ./backend/gen:/usr/src/app/gen
            - ./backend/src:/usr/src/app/src

    postgres:
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        volumes:
            - pgdata:/var/lib/postgresql/data

secrets:
    backend_accesstoken_keyfile:
        file: './backend/keys/ecdsa-p521-secret.pem'

volumes:
    pgdata: {}
